name: HamsterEcoHelper
main: cat.nyaa.HamsterEcoHelper.HamsterEcoHelper
description: "Provides a offer/buy system and global market."
version: ${version}
depend: [Vault,NyaaCore,LangUtils]
softdepend: [Essentials,LockettePro]
authors: [cyilin, RecursiveG]
website: "https://github.com/NyaaCat/HamsterEcoHelper"
api-version: 1.13
commands:
  hamsterecohelper:
    description: The command for HamsterEcoHelper
    aliases: [heh, h]
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
permissions:
  heh.command:
    default: true
    description: base permission for heh plugin
